import React, { useEffect, useState } from 'react';
import { Pressable, Share, StyleSheet, Text, View } from 'react-native';
import { colors, fonts, glass, strengthColor } from '../theme/tokens';
import { domainLabel } from '../lib/mockData';
import { coreStatusLabel } from '../lib/intelligenceStatus';
import type { Domain, RelationshipRef } from '../lib/types';
import type {
  CrossDomainUnderstandingRow,
  RelationshipRow,
  UnderstandingHistoryRow,
  UnderstandingRow,
} from '../lib/queries';
import { buildVisitBrief } from '../lib/visitPrep';
import { displayCopy } from '../lib/displayCopy';
import { insertObservation, type ProviderFeedbackRow } from '../lib/observations';
import type { Provider } from '../lib/providerSearch';
import BottomSheet from '../components/BottomSheet';
import RelationshipList from '../components/RelationshipList';
import Timeline from '../components/Timeline';
import TextField from '../components/TextField';
import PrimaryButton from '../components/PrimaryButton';
import GlassChip from '../components/GlassChip';
import GlassSurface, { GlassGroup } from '../components/GlassSurface';
import Card from '../components/Card';
import InsightVizHost from '../components/InsightVizHost';
import { CloseIcon } from '../components/icons';
import ProviderSearchSheet from './ProviderSearchSheet';

const CARE_TYPE_LABEL: Record<string, string> = {
  'primary-care': 'PRIMARY CARE',
  'ob-gyn': 'OB/GYN',
  'mental-health': 'MENTAL HEALTH',
};

// Closed-form outcomes only — the same discipline as careGuidance.ts's own
// enumerated maps. This is the "Outcome" half of Provider Feedback: what
// resulted, distinct from 'provider_assessment' (what the provider said).
// Never free text, never generated by Ciatta — the user picks one of
// these, or none at all.
const PROVIDER_OUTCOME: Record<string, string> = {
  confirmed: 'Confirmed something worth monitoring',
  'no-concern': 'No concern found',
  'care-started': 'Started some kind of care',
  inconclusive: 'Still unclear',
};

function formatFeedbackDate(value: string): string {
  return displayCopy(
    new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })
  );
}

function formatDate(value: string | null): string {
  if (!value) return '·';
  return displayCopy(
    new Date(value).toLocaleDateString(undefined, {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
    })
  );
}

/** "3 days" / "6 weeks" / "4 months" — a span someone can feel, not a date. */
function formatSpan(from: string | null): string | null {
  if (!from) return null;
  const days = Math.floor((Date.now() - new Date(from).getTime()) / 86400000);
  if (days < 1) return 'today';
  if (days < 14) return `${days} day${days === 1 ? '' : 's'}`;
  const weeks = Math.round(days / 7);
  if (days < 60) return `${weeks} weeks`;
  return `${Math.round(days / 30)} months`;
}

function formatProviderAddress(provider: Provider): string | null {
  const a = provider.address;
  if (!a) return null;
  const line2 = [a.city, a.state, a.postalCode].filter(Boolean).join(', ');
  return displayCopy([a.line1, line2].filter(Boolean).join(', ') || '') || null;
}

function formatAgo(value: string | null): string {
  if (!value) return '·';
  const mins = Math.floor((Date.now() - new Date(value).getTime()) / 60000);
  if (mins < 60) return mins <= 1 ? 'just now' : `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return days === 1 ? 'yesterday' : `${days} days ago`;
}

export default function UnderstandingSheet({
  domain,
  understandings,
  relationships,
  history,
  crossDomainUnderstandings,
  providerFeedback,
  userId,
  profileLocation,
  goals = [],
  onClose,
  onHelpLearnMore,
  onProviderFeedbackSaved,
  startWithProviderSearch = false,
}: {
  domain: Domain | null;
  understandings: UnderstandingRow[];
  relationships: RelationshipRow[];
  history: UnderstandingHistoryRow[];
  crossDomainUnderstandings: CrossDomainUnderstandingRow[];
  providerFeedback: ProviderFeedbackRow[];
  userId: string | null;
  profileLocation: string | null;
  goals?: string[];
  onClose: () => void;
  onHelpLearnMore: () => void;
  onProviderFeedbackSaved: () => void;
  startWithProviderSearch?: boolean;
}) {
  // Care Preparation / Provider Feedback / Provider Search state. Hooks run
  // unconditionally — this has to sit above the `!understanding` early
  // return below.
  const [loggingProvider, setLoggingProvider] = useState(false);
  const [providerNote, setProviderNote] = useState('');
  const [selectedOutcome, setSelectedOutcome] = useState<string | null>(null);
  const [savingProviderNote, setSavingProviderNote] = useState(false);
  const [providerNoteSaved, setProviderNoteSaved] = useState(false);
  const [careActionError, setCareActionError] = useState<string | null>(null);
  const [providerSearchOpen, setProviderSearchOpen] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState<Provider | null>(null);
  // null = the domain Understanding itself (the default, existing
  // behavior); a cross_domain_understandings id = one of "A BROADER
  // PATTERN"'s cards has claimed the shared care-action block below.
  // Every action (search/prepare/log) reads from `careTarget`, derived
  // below, rather than from `understanding` directly — the same three
  // handlers serve both cases, nothing is duplicated per-target.
  const [careTargetId, setCareTargetId] = useState<string | null>(null);

  useEffect(() => {
    if (domain && startWithProviderSearch) {
      setProviderSearchOpen(true);
    }
  }, [domain, startWithProviderSearch]);

  function handleClose() {
    setLoggingProvider(false);
    setProviderNote('');
    setSelectedOutcome(null);
    setProviderNoteSaved(false);
    setCareActionError(null);
    setProviderSearchOpen(false);
    setSelectedProvider(null);
    setCareTargetId(null);
    onClose();
  }

  const understanding = domain ? understandings.find((u) => u.domain === domain) ?? null : null;

  const relatedDomains: RelationshipRef[] = understanding
    ? relationships
        .filter((r) => r.from_domain === understanding.domain || r.to_domain === understanding.domain)
        .map((r) => ({
          domain: r.from_domain === understanding.domain ? r.to_domain : r.from_domain,
          strength: r.strength,
        }))
    : [];

  // Cross-Domain Understandings involving this domain — a stronger,
  // Guidance-eligible cousin of the plain "CONNECTED TO" relationships
  // above. Read straight off the row the Understanding Engine's
  // crossDomainSynthesis.ts wrote, same as everything else on this
  // screen — never recomputed client-side.
  const relatedCrossDomain = understanding
    ? crossDomainUnderstandings.filter(
        (cd) => cd.from_domain === understanding.domain || cd.to_domain === understanding.domain
      )
    : [];

  const timelineSteps = understanding
    ? history
        .filter((h) => h.understanding_id === understanding.id)
        .map((h, i, arr) => ({
          label: formatDate(h.event_date),
          detail: h.label,
          active: i === arr.length - 1,
        }))
    : [];

  if (!understanding) {
    return <BottomSheet visible={!!domain} onClose={handleClose}>{null}</BottomSheet>;
  }

  const span = formatSpan(understanding.learning_since);
  const confidence = coreStatusLabel(understanding);
  // Read straight off the row the Understanding Engine wrote — not
  // recomputed here, so there is exactly one place Guidance is derived.
  const guidance = understanding.guidance;
  // A non-null-typed alias for use inside nested closures below (handlePrepareVisit,
  // etc.) — TypeScript's null-narrowing from the early return above doesn't
  // carry into a nested function body's own reads of `understanding`.
  const understandingRow: UnderstandingRow = understanding;

  // Resolves whichever target a care action is for, given an explicit id
  // rather than trusting `careTargetId` state — a Pressable that both
  // sets the target and immediately triggers an action (e.g. a
  // cross-domain card's "Prepare for my visit") would otherwise read the
  // *previous* render's stale target, since setState doesn't apply until
  // the next render. Every handler below takes an explicit `targetId` and
  // resolves fresh from it; `careTargetId` state exists only to drive what
  // stays visible across renders (the logging form, the selected-provider
  // row, the feedback history) once a target has been chosen.
  //
  // Provider Search accepts either a domain or a cross-domain id directly
  // (see provider-search/index.ts's own fallback lookup), so
  // `providerSearchId` is whichever row is active. Provider Feedback
  // cannot: understanding_history.understanding_id is a foreign key into
  // `understandings` only, so a cross-domain target's feedback is
  // attributed to its from_domain contributor's real Understanding —
  // still correctly evidenced, still traceable, without a schema change.
  // Takes the current (already null-checked) Understanding explicitly
  // rather than closing over the outer `understanding` — TypeScript can't
  // carry the early-return null-check above into a nested function body,
  // and threading it through as a parameter is both the fix and, on its
  // own merits, one less implicit dependency for this function to have.
  function resolveCareTarget(currentUnderstanding: UnderstandingRow, targetId: string | null) {
    const cd = targetId ? relatedCrossDomain.find((c) => c.id === targetId) ?? null : null;
    const feedbackUnderstanding = cd
      ? understandings.find((u) => u.domain === cd.from_domain) ?? currentUnderstanding
      : currentUnderstanding;
    const careTarget = cd
      ? {
          displayLabel: `your ${displayCopy(cd.label).replace(/ related$/i, '').trim()} pattern`,
          domain: feedbackUnderstanding.domain,
          narrative: cd.narrative,
          confidenceLabel: cd.confidence_label ?? coreStatusLabel({ strength: cd.strength, confidence_label: cd.confidence_label }),
          // Cross-domain rows don't persist their own observation count —
          // it's the honest sum of what's already loaded for the two
          // domains that produced it, not a fabricated number.
          observationsCount:
            (understandings.find((u) => u.domain === cd.from_domain)?.observations_count ?? 0) +
            (understandings.find((u) => u.domain === cd.to_domain)?.observations_count ?? 0),
          learningSpan: formatSpan(cd.first_observed),
          stillLearning: cd.still_learning,
          guidance: cd.guidance,
          careRecommendationType: cd.care_recommendation_type,
          providerSearchId: cd.id,
        }
      : {
          displayLabel: `your ${domainLabel[currentUnderstanding.domain].toLowerCase()}`,
          domain: currentUnderstanding.domain,
          narrative: currentUnderstanding.narrative,
          confidenceLabel: confidence,
          observationsCount: currentUnderstanding.observations_count,
          learningSpan: span,
          stillLearning: currentUnderstanding.still_learning,
          guidance: currentUnderstanding.guidance,
          careRecommendationType: currentUnderstanding.care_recommendation_type,
          providerSearchId: currentUnderstanding.id,
        };
    return { careTarget, feedbackUnderstanding };
  }

  // What's actually displayed — the currently-selected target, or the
  // domain itself by default.
  const { careTarget, feedbackUnderstanding } = resolveCareTarget(understandingRow, careTargetId);

  // Past feedback scoped to whichever real Understanding feedback for the
  // current target is actually attributed to — the domain's own when no
  // cross-domain target is active, its from_domain contributor otherwise.
  const targetFeedback = providerFeedback.filter(
    (f) => f.context?.understandingId === feedbackUnderstanding.id
  );

  function handleSelectProvider(provider: Provider) {
    setSelectedProvider(provider);
    setProviderSearchOpen(false);
  }

  async function handlePrepareVisit(targetId: string | null) {
    setCareActionError(null);
    const { careTarget, feedbackUnderstanding } = resolveCareTarget(understandingRow, targetId);
    const brief = buildVisitBrief({
      domainLabel: domainLabel[careTarget.domain],
      narrative: careTarget.narrative,
      confidenceLabel: careTarget.confidenceLabel,
      observationsCount: careTarget.observationsCount,
      learningSpan: careTarget.learningSpan,
      timelineSteps: timelineSteps.map((s) => ({ label: s.label, detail: s.detail })),
      stillLearning: careTarget.stillLearning,
      guidance: careTarget.guidance,
      provider: selectedProvider
        ? {
            name: selectedProvider.name,
            specialty: selectedProvider.specialty[0] ?? null,
            address: formatProviderAddress(selectedProvider),
            phone: selectedProvider.phone,
          }
        : null,
    });
    try {
      await Share.share({ message: brief });
      // The brief itself is never stored — it's assembled fresh from data
      // already on screen. What's worth remembering is that preparing one
      // happened at all, logged the same way every other user action in
      // this app already is: as a manual Observation. Always attributed to
      // a real Understanding (feedbackUnderstanding), even when the brief
      // itself described a cross-domain pattern.
      if (userId) {
        await insertObservation(userId, {
          source: 'manual',
          type: 'visit_prep_shared',
          value: { domain: feedbackUnderstanding.domain },
          context: {
            understandingId: feedbackUnderstanding.id,
            // Provenance for which provider (if any) this brief named —
            // an external directory id, not a claim about who the user
            // actually saw.
            providerId: selectedProvider?.id ?? null,
            providerSource: selectedProvider?.source ?? null,
          },
        });
        onProviderFeedbackSaved();
      }
    } catch (e) {
      setCareActionError(e instanceof Error ? e.message : "That didn't go through. Try again.");
    }
  }

  async function handleSaveProviderNote() {
    if (!userId) return;
    const note = providerNote.trim();
    if (!note && !selectedOutcome) return;
    setSavingProviderNote(true);
    setCareActionError(null);
    try {
      const recordedAt = new Date().toISOString();
      const writes: Promise<void>[] = [];
      if (note) {
        // 'provider' is its own provenance, distinct from 'manual' — this is
        // what a provider determined, relayed by the user, not the user's
        // own unprompted observation. Feeds back into the same Observations
        // table every other source already writes to, so a future
        // Understanding Engine run can draw on it like any other evidence
        // (see processProviderFeedbackEvidence() in the Understanding
        // Engine). Always attributed to feedbackUnderstanding — a real
        // Understanding row, even when the active care target is a
        // cross-domain pattern.
        writes.push(
          insertObservation(userId, {
            source: 'provider',
            type: 'provider_assessment',
            value: { text: note },
            recordedAt,
            context: { domain: feedbackUnderstanding.domain, understandingId: feedbackUnderstanding.id },
          })
        );
      }
      if (selectedOutcome) {
        // The Outcome half of Provider Feedback — a closed-form result,
        // never free text, kept as its own Observation type so "what the
        // provider said" and "what actually resulted" stay distinguishable
        // by type, not just by reading the sentence. Same 'provider'
        // provenance and same understandingId linkage as the assessment
        // above; a distinct recordedAt (offset by 1s) only so the two never
        // collide on this table's (user_id, source, type, recorded_at)
        // uniqueness — they're type-distinct anyway, but this keeps them
        // orderable if ever queried together.
        writes.push(
          insertObservation(userId, {
            source: 'provider',
            type: 'provider_outcome',
            value: { outcome: selectedOutcome },
            recordedAt: new Date(Date.parse(recordedAt) + 1000).toISOString(),
            context: { domain: feedbackUnderstanding.domain, understandingId: feedbackUnderstanding.id },
          })
        );
      }
      await Promise.all(writes);
      setProviderNote('');
      setSelectedOutcome(null);
      setProviderNoteSaved(true);
      setLoggingProvider(false);
      onProviderFeedbackSaved();
    } catch (e) {
      setCareActionError(e instanceof Error ? e.message : "That didn't save. Try again.");
    } finally {
      setSavingProviderNote(false);
    }
  }

  return (
    <>
    <BottomSheet visible={!!domain} onClose={handleClose}>
      <View>
        <View style={styles.headerRow}>
          <View style={styles.headerText}>
            <Text style={styles.title}>{domainLabel[understanding.domain]}</Text>
          </View>
          <Pressable onPress={handleClose} hitSlop={10}>
            <CloseIcon />
          </Pressable>
        </View>

        {/* The finding itself, given the weight it deserves. */}
        <Text style={styles.narrative}>{understanding.seeing || understanding.narrative}</Text>

        {/* Confidence, stated once, where it belongs — next to the claim it
            qualifies rather than buried in a stat table below. */}
        <View style={styles.confidenceRow}>
          <View
            style={[
              styles.confidenceDot,
              { backgroundColor: strengthColor[understanding.strength] },
            ]}
          />
          <Text style={[styles.confidenceText, { color: strengthColor[understanding.strength] }]}>
            {confidence}
          </Text>
          <Text style={styles.confidenceSep}>·</Text>
          <Text style={styles.confidenceMeta}>updated {formatAgo(understanding.last_updated)}</Text>
        </View>

        {userId && domain ? (
          <View style={styles.viz}>
            <InsightVizHost
              userId={userId}
              understandings={understandings}
              relationships={relationships}
              goals={goals}
              featuredDomain={understanding.domain}
              focusDomain={understanding.domain}
            />
          </View>
        ) : null}

        <Text style={styles.sectionLabel}>THE EVIDENCE</Text>
        <View style={styles.evidenceStrip}>
          <View style={styles.metric}>
            <Text style={styles.metricValue}>{understanding.observations_count}</Text>
            <Text style={styles.metricLabel}>readings{'\n'}behind this</Text>
          </View>
          <View style={styles.metricDivider} />
          <View style={styles.metric}>
            <Text style={styles.metricValue}>{span ?? '·'}</Text>
            <Text style={styles.metricLabel}>of this{'\n'}pattern</Text>
          </View>
          <View style={styles.metricDivider} />
          <View style={styles.metric}>
            <Text style={styles.metricValue}>{timelineSteps.length || '·'}</Text>
            <Text style={styles.metricLabel}>time{timelineSteps.length === 1 ? '' : 's'} this{'\n'}has shifted</Text>
          </View>
        </View>
        <Text style={styles.evidenceFootnote}>
          Learning since {formatDate(understanding.learning_since)}.
        </Text>

        {relatedDomains.length > 0 ? (
          <>
            <Text style={styles.sectionLabel}>CONNECTED TO</Text>
            <RelationshipList relationships={relatedDomains} />
          </>
        ) : null}

        {relatedCrossDomain.length > 0 ? (
          <>
            <Text style={styles.sectionLabel}>A BROADER PATTERN</Text>
            {relatedCrossDomain.map((cd) => {
              const otherDomain = cd.from_domain === understanding.domain ? cd.to_domain : cd.from_domain;
              return (
                <Card key={cd.id} style={styles.crossDomainCard}>
                  <View style={styles.confidenceRow}>
                    <View
                      style={[styles.confidenceDot, { backgroundColor: strengthColor[cd.strength] }]}
                    />
                    <Text style={[styles.confidenceText, { color: strengthColor[cd.strength] }]}>
                      {coreStatusLabel({ strength: cd.strength, confidence_label: cd.confidence_label })}
                    </Text>
                    <Text style={styles.confidenceSep}>·</Text>
                    <Text style={styles.confidenceMeta}>
                      with your {domainLabel[otherDomain]}
                    </Text>
                  </View>
                  <Text style={styles.crossDomainNarrative}>{cd.narrative}</Text>
                  {cd.guidance ? <Text style={styles.bulletText}>{cd.guidance}</Text> : null}
                  {userId && cd.guidance ? (
                    <View style={styles.careActions}>
                      <Pressable
                        onPress={() => {
                          setCareTargetId(cd.id);
                          setProviderSearchOpen(true);
                        }}
                        hitSlop={8}
                      >
                        <Text style={styles.careActionLink}>Talk with a provider</Text>
                      </Pressable>
                      <Pressable onPress={() => handlePrepareVisit(cd.id)} hitSlop={8}>
                        <Text style={styles.careActionLink}>Prepare for my visit</Text>
                      </Pressable>
                      <Pressable
                        onPress={() => {
                          setCareTargetId(cd.id);
                          setLoggingProvider((v) => (careTargetId === cd.id ? !v : true));
                        }}
                        hitSlop={8}
                      >
                        <Text style={styles.careActionLink}>Log provider feedback</Text>
                      </Pressable>
                    </View>
                  ) : null}
                </Card>
              );
            })}
          </>
        ) : null}

        {timelineSteps.length > 0 ? (
          <>
            <Text style={styles.sectionLabel}>HOW THIS CHANGED</Text>
            <Timeline steps={timelineSteps} />
          </>
        ) : null}

        {understanding.still_learning.length > 0 ? (
          <>
            <Text style={styles.sectionLabel}>STILL LEARNING</Text>
            {understanding.still_learning.map((q) => (
              <View key={q} style={styles.bulletRow}>
                <View style={styles.bullet} />
                <Text style={styles.bulletText}>{q}</Text>
              </View>
            ))}
          </>
        ) : null}

        {guidance ? (
          <>
            <Text style={styles.sectionLabel}>FOR A VISIT</Text>
            {understanding.care_recommendation_reason ? (
              <Text style={styles.bulletText}>{understanding.care_recommendation_reason}</Text>
            ) : null}
            {understanding.care_recommendation_type ? (
              <Text style={styles.careTypeBadge}>
                {CARE_TYPE_LABEL[understanding.care_recommendation_type] ??
                  understanding.care_recommendation_type}
              </Text>
            ) : null}
            <Text style={styles.bulletText}>{guidance}</Text>

            {userId ? (
              <View style={styles.careActions}>
                <Pressable
                  onPress={() => {
                    setCareTargetId(null);
                    setProviderSearchOpen(true);
                  }}
                  hitSlop={8}
                >
                  <Text style={styles.careActionLink}>Talk with a provider</Text>
                </Pressable>
                <Pressable onPress={() => handlePrepareVisit(null)} hitSlop={8}>
                  <Text style={styles.careActionLink}>Prepare for my visit</Text>
                </Pressable>
                <Pressable
                  onPress={() => {
                    setCareTargetId(null);
                    setLoggingProvider((v) => (careTargetId === null ? !v : true));
                  }}
                  hitSlop={8}
                >
                  <Text style={styles.careActionLink}>Log what your provider said</Text>
                </Pressable>
              </View>
            ) : null}

            {careTargetId ? (
              <Text style={styles.careTargetIndicator}>For {careTarget.displayLabel}</Text>
            ) : null}

            {selectedProvider ? (
              <GlassSurface
                kind="regular"
                tintColor={glass.tint}
                colorScheme="auto"
                style={styles.selectedProviderRow}
                fallbackStyle={styles.selectedProviderFallback}
              >
                <Text style={styles.selectedProviderText}>
                  Preparing for: {selectedProvider.name}
                  {selectedProvider.specialty[0] ? `, ${selectedProvider.specialty[0]}` : ''}
                </Text>
                <Pressable onPress={() => setSelectedProvider(null)} hitSlop={8}>
                  <Text style={styles.selectedProviderClear}>Clear</Text>
                </Pressable>
              </GlassSurface>
            ) : null}

            {loggingProvider ? (
              <View style={{ marginTop: 12 }}>
                <TextField
                  value={providerNote}
                  onChangeText={setProviderNote}
                  placeholder="What did your provider say?"
                  multiline
                />
                <Text style={styles.outcomeLabel}>WHAT WAS THE OUTCOME?</Text>
                <GlassGroup spacing={8} style={styles.outcomeOptions}>
                  {Object.entries(PROVIDER_OUTCOME).map(([key, label]) => (
                    <GlassChip
                      key={key}
                      label={label}
                      selected={selectedOutcome === key}
                      onPress={() => setSelectedOutcome((v) => (v === key ? null : key))}
                    />
                  ))}
                </GlassGroup>
                <View style={{ marginTop: 10 }}>
                  <PrimaryButton
                    label="Save"
                    onPress={handleSaveProviderNote}
                    loading={savingProviderNote}
                    disabled={!providerNote.trim() && !selectedOutcome}
                  />
                </View>
              </View>
            ) : null}

            {providerNoteSaved ? (
              <Text style={styles.careConfirmation}>Added to your understanding.</Text>
            ) : null}
            {careActionError ? <Text style={styles.careError}>{careActionError}</Text> : null}

            {targetFeedback.length > 0 ? (
              <View style={styles.feedbackHistory}>
                <Text style={styles.outcomeLabel}>WHAT'S BEEN LOGGED</Text>
                {targetFeedback.map((f) => (
                  <View key={f.id} style={styles.bulletRow}>
                    <View style={styles.bullet} />
                    <Text style={styles.bulletText}>
                      {formatFeedbackDate(f.recorded_at)}:{' '}
                      {f.type === 'provider_outcome'
                        ? PROVIDER_OUTCOME[f.value.outcome as string] ?? String(f.value.outcome)
                        : String(f.value.text ?? '')}
                    </Text>
                  </View>
                ))}
              </View>
            ) : null}
          </>
        ) : null}

        <View style={{ marginTop: 28 }}>
          <PrimaryButton label="Share a little more" onPress={onHelpLearnMore} />
        </View>
      </View>
    </BottomSheet>
    <ProviderSearchSheet
      visible={providerSearchOpen}
      understandingId={careTarget.providerSearchId}
      careRecommendationType={careTarget.careRecommendationType}
      profileLocation={profileLocation}
      onClose={() => setProviderSearchOpen(false)}
      onSelectProvider={handleSelectProvider}
    />
    </>
  );
}

const styles = StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  headerText: {
    flex: 1,
    paddingRight: 12,
  },
  eyebrow: {
    ...fonts.sansMedium,
    fontSize: 10.5,
    letterSpacing: 1.1,
    color: colors.ink3,
    marginBottom: 4,
  },
  title: {
    ...fonts.serif,
    fontSize: 14,
    lineHeight: 18,
    color: colors.ink,
  },
  narrative: {
    ...fonts.sans,
    fontSize: 14.5,
    lineHeight: 22,
    color: colors.ink,
  },
  confidenceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    marginTop: 14,
    flexWrap: 'wrap',
  },
  confidenceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  confidenceText: {
    ...fonts.sansSemiBold,
    fontSize: 13,
  },
  confidenceSep: {
    ...fonts.sans,
    fontSize: 13,
    color: colors.ink3,
  },
  confidenceMeta: {
    ...fonts.sans,
    fontSize: 13,
    color: colors.ink3,
  },
  sectionLabel: {
    ...fonts.sansMedium,
    fontSize: 10.5,
    letterSpacing: 1.1,
    color: colors.ink3,
    marginTop: 30,
    marginBottom: 12,
  },
  viz: {
    marginTop: 18,
  },
  evidenceStrip: {
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: colors.wash,
    borderRadius: 14,
    paddingVertical: 18,
  },
  metric: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  metricDivider: {
    width: 1,
    backgroundColor: colors.border,
    marginVertical: 2,
  },
  metricValue: {
    ...fonts.mono,
    fontSize: 20,
    color: colors.evidence,
  },
  metricLabel: {
    ...fonts.sans,
    fontSize: 11.5,
    lineHeight: 15,
    color: colors.ink2,
    textAlign: 'center',
    marginTop: 6,
  },
  evidenceFootnote: {
    ...fonts.sans,
    fontSize: 12,
    color: colors.ink3,
    marginTop: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
    gap: 8,
  },
  bullet: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.ink3,
    marginTop: 8,
  },
  bulletText: {
    flex: 1,
    ...fonts.sans,
    fontSize: 13.5,
    lineHeight: 20,
    color: colors.ink2,
  },
  careTypeBadge: {
    ...fonts.sansSemiBold,
    fontSize: 10.5,
    letterSpacing: 0.8,
    color: colors.accent,
    marginBottom: 6,
  },
  careActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 18,
    marginTop: 12,
  },
  careActionLink: {
    ...fonts.sansMedium,
    fontSize: 13,
    color: colors.ink,
  },
  careConfirmation: {
    ...fonts.sans,
    fontSize: 13,
    color: colors.evidence,
    marginTop: 12,
  },
  careError: {
    ...fonts.sans,
    fontSize: 13,
    color: colors.accent,
    marginTop: 10,
  },
  selectedProviderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginTop: 12,
  },
  selectedProviderFallback: {
    backgroundColor: colors.wash,
    borderRadius: 10,
  },
  selectedProviderText: {
    flex: 1,
    ...fonts.sansMedium,
    fontSize: 12.5,
    color: colors.ink,
    paddingRight: 10,
  },
  selectedProviderClear: {
    ...fonts.sansMedium,
    fontSize: 12.5,
    color: colors.ink3,
    textDecorationLine: 'underline',
  },
  crossDomainCard: {
    padding: 14,
    marginBottom: 10,
  },
  crossDomainNarrative: {
    ...fonts.serif,
    fontSize: 15.5,
    lineHeight: 21,
    color: colors.ink,
    marginTop: 8,
    marginBottom: 6,
  },
  outcomeLabel: {
    ...fonts.sansMedium,
    fontSize: 10.5,
    letterSpacing: 1.1,
    color: colors.ink3,
    marginTop: 14,
    marginBottom: 8,
  },
  outcomeOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  feedbackHistory: {
    marginTop: 16,
  },
  careTargetIndicator: {
    ...fonts.sansMedium,
    fontSize: 12,
    color: colors.ink3,
    marginTop: 10,
  },
});
